spring:
  datasource:
    driver-class-name: MongoDB
  data:
    mongodb:
      database: simpson-database
      host: mongodb
      port: 27017
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
          facebook:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}

server:
  port: 8081
  servlet:
    context-path: /resource-server


